### ISSUE TITLE
Using custom webfont w/ gem

### ISSUE THREAD

**Issue by pixxelboy** [maxd/less-rails-semantic_ui#10]
Hi, just wondering how things get tied up when it comes to importing a custom webfont (i.e not Google Font) and using it in the site.variables file ?

Thanks for your support!

**Comment by maxd** [comment]
Just disable Google font (look at [this](https://github.com/maxd/less-rails-semantic_ui/blob/2d0e8f25c112122a870bf3819a9d7db8f5b67a40/assets/stylesheets/semantic_ui/themes/default/globals/site.variables#L13) and [this](https://github.com/maxd/less-rails-semantic_ui/blob/2d0e8f25c112122a870bf3819a9d7db8f5b67a40/assets/stylesheets/semantic_ui/theme.less#L37)) and import own font.
