### ISSUE TITLE
Modals do not work on Chrome, Safari

### ISSUE THREAD

**Issue by arnav90** [maxd/less-rails-semantic_ui#6]
Hi,
I'm using less-rails-semantic_ui with rails 4.1.8. While trying to open a modal on chrome/safari, I get the following console errors and the modal fails to open:
There is no css animation matching the one you specified. fade in 
There is no css animation matching the one you specified. scale in 

This works fine in firefox.

**Comment by maxd** [comment]
Could you please provide a simple Rails application for reproduce problem?

**Comment by arnav90** [comment]
You can see it [here] (https://github.com/arnav90/test-app) .
Also, these are the browser versions that I'm using:

Chrome : OSX,  40.0.2214.111 (64-bit)
Safari: OSX, Version 8.0.3 (10600.3.18)
Firefox:  OSX, 35.0.1

**Comment by maxd** [comment]
Thank you a lot for providing application with example of problem. 

You problem has been discussed in PR #5. For resolve you problem just add `autoprefixer-rails` gem to your Gemfile. To avoid such problems in the future I have updated README.

**Comment by arnav90** [comment]
Awesome, Thanks
